### ISSUE TITLE
Update README for Improved Documentation

### ISSUE THREAD

**Issue by jinx-vi-0** [Mayank2808sharma/IRCTC-backend#22]
Clear and well-structured documentation is crucial for users and contributors to understand the project, its purpose, and how to get started.

hey @Mayank2808sharma , please assing this issue to me.

**Comment by Mayank2808sharma** [comment]
There is already a readme
what changes are you thinking to make?

**Comment by d1vyadharsh1n1** [comment]
@Mayank2808sharma I would like to add tech stack and also mention about girlscript summer of code along in the readme file

**Comment by jinx-vi-0** [comment]
hey @Mayank2808sharma , the current readme is not visually appealing , I propose to make it more interactive by adding features like stars count, issue count, pr count, etc and contributors section.

**Comment by Mayank2808sharma** [comment]
@jinx-vi-0 
go ahead

**Comment by jinx-vi-0** [comment]
hey @Mayank2808sharma , I have created a pr, please check it and let me know for any feedback.
