### ISSUE TITLE
You Have to start the app again and again after updating or writing code.

### ISSUE THREAD

**Issue by Adeebahmed333** [Mayank2808sharma/IRCTC-backend#24]
I want to add some package and scripts so that we don't have to start the app again and again after writing or updating the code.

**Comment by ShoveetSingh** [comment]
Hey mate there are various node packages that automatically restarts your application when any changes are made to it.
Some of them are nodemon,pm2(package manager),forever,etc.
I can try to fix your issue if assigned with the task.
Shoveet here.

**Comment by Mayank2808sharma** [comment]
@Adeebahmed333 I have assigned the issue to you.

**Comment by Adeebahmed333** [comment]
> @Adeebahmed333 I have assigned the issue to you.

okay, I will submit the pr till evening.
