### ISSUE TITLE
Adding mailing service when any booking is confirmed or made!

### ISSUE THREAD

**Issue by ShoveetSingh** [Mayank2808sharma/IRCTC-backend#25]
Hey mate Shoveet here,There is a npm package named as nodemailer which seamlessly sends email to the target gmail address once it has recieved data in json format at a praticular route.
Been working with node from past few years.
Can solve the problem related with node js(backend).

**Comment by Mayank2808sharma** [comment]
@ShoveetSingh 
Some one is already working on this.
