### ISSUE TITLE
Request input validations should be implemented.

### ISSUE THREAD

**Issue by harsh-haria** [Mayank2808sharma/IRCTC-backend#34]
We should add a middleware for all the endpoints that checks for the inputs that are required for a particular endpoint.
If any of the inputs are missing(if required) or are not of the correct type, the server should return the response to the client with the issue without processing anything in the controller.
Sever side validations will decrease the chance of server returning 5XX errors.
I would be more than happy to help with this issue.
Can you please assign this issue to me under GSSOC 2024 ?

**Comment by Mayank2808sharma** [comment]
@harsh-haria 
Some one is already working on that
