### ISSUE TITLE
Validation to ensure the strong password

### ISSUE THREAD

**Issue by farzaneh-haghani** [Mayank2808sharma/IRCTC-backend#38]
Hi there,
I'm a GSSOC'24 contributor. I tried to registered with password: "test" in the app and accepted. 
Could you please assign this issue to me.

Given I am a user
When I enter a weak password
Then I should not be able to register and should get a message to make it strong.

validation:
1. Length should be at least 8 characters.
2. Complexity should contain a mix of uppercase, lowercase, numbers and special characters.

**Comment by Nirvanjha2004** [comment]
Let me work on this issue....

**Comment by Mayank2808sharma** [comment]
@farzaneh-haghani 
Go ahead, I have assigned the issue to you.
